In [3]:
import numpy as np
import pandas as pd

movie_reviews=pd.read_csv("C:\\Users\Windows\_ANCONDA WORKSHOP\_VAMSHI SIR\datasets\EA.csv")

movie_reviews.head(5)

,Unnamed: 0,score_phrase,title,url,platform,score,genre,editors_choice,release_year,release_month,release_day
0,0,Amazing,LittleBigPlanet PS Vita,/games/littlebigplanet-vita/vita-98907,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,/games/littlebigplanet-ps-vita-marvel-super-he...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,2,Great,Splice: Tree of Life,/games/splice/ipad-141070,iPad,8.5,Puzzle,N,2012,9,12
3,3,Great,NHL 13,/games/nhl-13/xbox-360-128182,Xbox 360,8.5,Sports,N,2012,9,11
4,4,Great,NHL 13,/games/nhl-13/ps3-128181,PlayStation 3,8.5,Sports,N,2012,9,11

In [8]:
Xbox_one_filter=(movie_reviews['score']>7)&(movie_reviews['platform']=='Xbox One')
filtered_reviews=movie_reviews[Xbox_one_filter]
filtered_reviews.head(3)

,Unnamed: 0,score_phrase,title,url,platform,score,genre,editors_choice,release_year,release_month,release_day
17137,17137,Amazing,Gone Home,/games/gone-home/xbox-one-20014361,Xbox One,9.5,Simulation,Y,2013,8,15
17197,17197,Amazing,Rayman Legends,/games/rayman-legends/xbox-one-20008449,Xbox One,9.5,Platformer,Y,2013,8,26
17295,17295,Amazing,LEGO Marvel Super Heroes,/games/lego-marvel-super-heroes/xbox-one-20000826,Xbox One,9.0,Action,Y,2013,10,22

In [27]:
platform_group = movie_reviews.groupby('platform')
platform_group.groups

{'Android': Int64Index([   84,   132,   141, 14741, 14742, 14743, 14744, 14745, 14752,
             14753, 14754, 14783, 14784, 14785, 14924, 14940, 14945, 14956,
             14963, 14981, 14993, 15063, 15561, 15816, 16225, 16462, 16539,
             16816, 16903, 17070, 17085, 17476, 17523, 17558, 17684, 18012,
             18032, 18196, 18599],
            dtype='int64'),
 'Arcade': Int64Index([2217, 10723, 12760, 12775, 12789, 13060, 13252, 13451, 13678,
             13701, 16766],
            dtype='int64'),
 'Atari 2600': Int64Index([10778, 11278, 11279, 11296, 11353], dtype='int64'),
 'Atari 5200': Int64Index([10464, 10521], dtype='int64'),
 'Commodore 64/128': Int64Index([11176, 12533, 12537, 12686, 12865, 13449], dtype='int64'),
 'DVD / HD Video Game': Int64Index([4026], dtype='int64'),
 'Dreamcast': Int64Index([1457, 1488, 1489, 1490, 1491, 1492, 1493, 1498, 1499, 1500,
             ...
             3372, 3390, 3392, 3399, 3484, 3551, 3625, 3626, 3643, 7979],
            dtype='int64', length=286),
 'Dreamcast VMU': Int64Index([1620], dtype='int64'),
 'Game Boy': Int64Index([ 1284,  1285,  1287,  1288,  1289,  1290,  1296,  1300,  1301,
              1302,  1313,  1314,  1317,  1326,  1329,  1672,  2232,  2234,
              2299,  2328,  2360, 11232],
            dtype='int64'),
 'Game Boy Advance': Int64Index([3150, 3151, 3152, 3153, 3154, 3189, 3191, 3194, 3199, 3200,
             ...
             8793, 8796, 8856, 8877, 8943, 8944, 8984, 9002, 9093, 9515],
            dtype='int64', length=623),
 'Game Boy Color': Int64Index([1304, 1312, 1327, 1331, 1345, 1394, 1412, 1413, 1415, 1417,
             ...
             3404, 3415, 3419, 3476, 3516, 3564, 3585, 3661, 3899, 4253],
            dtype='int64', length=356),
 'Game.Com': Int64Index([1396, 1442, 1570], dtype='int64'),
 'GameCube': Int64Index([3450, 3451, 3452, 3454, 3457, 3479, 3482, 3492, 3499, 3511,
             ...
             8406, 8474, 8487, 8707, 8755, 9059, 9075, 9135, 9619, 9642],
            dtype='int64', length=509),
 'Genesis': Int64Index([ 8659,  8729,  8747,  8774,  8813,  8863,  8900,  8907,  8951,
              8977,  9142,  9406,  9466,  9525,  9613,  9765,  9771, 10172,
             10255, 10358, 10409, 10420, 10457, 10475, 10503, 10507, 10545,
             10640, 10650, 10686, 10809, 10818, 10823, 10882, 10909, 10968,
             10970, 11059, 11062, 11247, 11256, 11648, 11669, 11710, 11747,
             11922, 11967, 12064, 12091, 12362, 12411, 12521, 12826, 12840,
             12927, 13090, 13226, 13265],
            dtype='int64'),
 'Linux': Int64Index([352, 17075, 17139, 17191, 17247, 17260, 17353, 17430, 17739,
             18175],
            dtype='int64'),
 'Lynx': Int64Index([1250, 1267, 1268, 1269, 1271, 1272, 1305, 1306, 1307, 1308, 1309,
             1310, 1320, 1321, 1322, 1323, 1324, 1325, 1335, 1336, 1337, 1338,
             1339, 1340, 1341, 1342, 1343, 1347, 1348, 1350, 1351, 1352, 1353,
             1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364,
             1366, 1367, 1368, 1369, 1370, 1371, 1372, 1375, 1376, 1377, 1378,
             1379, 1381, 1382, 1383, 1384, 1385, 1386, 1388, 1389, 1390, 1391,
             1392, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408,
             1418, 1587, 1600, 2981, 3015],
            dtype='int64'),
 'Macintosh': Int64Index([    5,    15,    30,    41,    82,   126,   245,   248,   306,
               350,  3786,  3787,  3788,  3890,  3891,  3902,  3903,  3904,
              3905,  3906,  3907,  3908,  3919,  3923,  3924,  3925,  3926,
              3927,  3928,  3929,  3930,  3939,  3940,  3942,  3943,  3953,
              3954,  3967,  3987,  4039,  4052,  4058,  4073,  4108,  4409,
              4419,  4485,  4543,  4668,  4670, 16707, 16735, 16753, 16825,
             16876, 16945, 16961, 17067, 17073, 17076, 17102, 17104, 17136,
             17142, 17193, 17246, 17262, 17321, 17352, 17422, 17431, 17559,
             17614, 17641, 17714, 17740, 18035, 18108, 18177, 18281, 18418],
            dtype='int64'),
 'Master System': Int64Index([10415, 10489, 10512, 10893, 11763, 11861, 12178, 12309, 12448,
             12483, 13193, 13199, 13384],
            dtype='int64'),
 'N-Gage': Int64Index([5081, 5119, 5158, 5159, 5160, 5173, 5188, 5206, 5450, 5479, 5539,
             5551, 5568, 5696, 5912, 5925, 5927, 5981, 6022, 6538, 6555, 6573,
             6595, 6856, 6858, 7267, 7497, 7515, 7591, 7659],
            dtype='int64'),
 'NES': Int64Index([ 7346,  8633,  8641,  8673,  8723,  8767,  8905,  8968,  9029,
              9032,  9042,  9078,  9173,  9176,  9236,  9280,  9301,  9304,
              9372,  9380,  9418,  9480,  9533,  9577,  9587,  9712,  9761,
              9826,  9891,  9983, 10046, 10374, 10396, 10427, 10458, 10502,
             10558, 10578, 10691, 10858, 10869, 10879, 11006, 11848, 12358,
             12364, 12584, 13413, 13534],
            dtype='int64'),
 'NeoGeo': Int64Index([9837, 10059, 10104, 10176, 10478, 11066, 11082, 11607, 11623,
             12503],
            dtype='int64'),
 'NeoGeo Pocket Color': Int64Index([1393, 1397, 1398, 1435, 1437, 1440, 1444, 1447, 1448, 1460, 1465,
             1470, 1483, 1537, 1588, 1589, 1794, 1842, 1927, 1933, 2001, 2004,
             2020, 2021, 2025, 2158, 2173, 2204, 2205, 2222, 2352],
            dtype='int64'),
 'New Nintendo 3DS': Int64Index([18095, 18492], dtype='int64'),
 'Nintendo 3DS': Int64Index([   68,   135,   143,   169,   203,   234,   236,   239,   269,
               302,
             ...
             18391, 18465, 18471, 18484, 18545, 18574, 18592, 18609, 18612,
             18614],
            dtype='int64', length=225),
 'Nintendo 64': Int64Index([ 483,  484,  486,  488,  514,  525,  539,  542,  566,  570,
             ...
             3006, 3010, 3046, 3054, 3112, 3128, 3129, 3173, 3433, 3684],
            dtype='int64', length=302),
 'Nintendo 64DD': Int64Index([2341, 2371, 2372, 2381, 2385, 2510, 2545], dtype='int64'),
 'Nintendo DS': Int64Index([   33,    35,  6356,  6358,  6369,  6409,  6410,  6428,  6438,
              6473,
             ...
             16094, 16119, 16122, 16152, 16166, 16174, 16180, 16237, 16400,
             16740],
            dtype='int64', length=1045),
 'Nintendo DSi': Int64Index([12741, 12746, 12750, 12771, 12772, 12773, 12806, 12841, 12878,
             12889,
             ...
             16417, 16418, 16442, 16443, 16444, 16449, 16486, 16501, 16518,
             16520],
            dtype='int64', length=254),
 'Ouya': Int64Index([17550], dtype='int64'),
 'PC': Int64Index([    7,     9,    14,    16,    23,    24,    25,    27,    28,
                31,
             ...
             18596, 18598, 18600, 18603, 18606, 18613, 18616, 18618, 18619,
             18624],
            dtype='int64', length=3370),
 'PlayStation': Int64Index([ 400,  401,  402,  403,  404,  405,  406,  407,  408,  409,
             ...
             3948, 4019, 4065, 4074, 4104, 4122, 4377, 4570, 4586, 4728],
            dtype='int64', length=952),
 'PlayStation 2': Int64Index([ 2550,  2551,  2552,  2553,  2556,  2557,  2558,  2559,  2560,
              2562,
             ...
             13817, 13848, 13959, 13968, 14062, 14094, 14297, 14305, 14968,
             15083],
            dtype='int64', length=1686),
 'PlayStation 3': Int64Index([    4,     8,    10,    18,    20,    22,    29,    32,    39,
                42,
             ...
             17968, 18000, 18016, 18020, 18038, 18041, 18139, 18250, 18327,
             18528],
            dtype='int64', length=1356),
 'PlayStation 4': Int64Index([  192, 17049, 17123, 17140, 17160, 17185, 17195, 17224, 17298,
             17305,
             ...
             18593, 18594, 18601, 18604, 18605, 18608, 18610, 18617, 18621,
             18622],
            dtype='int64', length=277),
 'PlayStation Portable': Int64Index([  383,  6631,  6633,  6636,  6639,  6657,  6675,  6681,  6682,
              6683,
             ...
             15685, 15710, 15731, 15790, 16163, 16310, 16382, 16437, 16687,
             16841],
            dtype='int64', length=633),
 'PlayStation Vita': Int64Index([    0,     1,    56,    88,    91,   101,   129,   136,   144,
               150,
             ...
             18091, 18138, 18153, 18240, 18324, 18365, 18367, 18563, 18569,
             18615],
            dtype='int64', length=155),
 'Pocket PC': Int64Index([4779], dtype='int64'),
 'Saturn': Int64Index([485, 515, 10622, 11294, 11365, 11410], dtype='int64'),
 'Sega 32X': Int64Index([10878, 11798, 11951, 11970, 11971, 12007, 12024, 12039, 12069,
             12082, 12098, 12134, 12146, 12166, 12189, 12198],
            dtype='int64'),
 'Sega CD': Int64Index([11237], dtype='int64'),
 'SteamOS': Int64Index([18160], dtype='int64'),
 'Super NES': Int64Index([ 8842,  8911,  8969,  9159,  9247,  9326,  9389,  9621,  9727,
              9814, 10027, 10234, 10353, 10360, 10405, 10586, 10844, 10927,
             11168, 11233, 11596, 11647, 11977, 12361, 12622, 12665, 12833,
             12871, 13324, 13329, 13407, 13686, 13723],
            dtype='int64'),
 'TurboGrafx-16': Int64Index([ 8670,  8720,  8724,  8861,  8929,  8958,  8963,  9014,  9067,
              9152,  9165,  9172,  9201,  9235,  9282,  9321,  9351,  9386,
              9445,  9451,  9464,  9542,  9550,  9602,  9609,  9630,  9749,
              9781,  9944, 10022, 10103, 10364, 10819, 10833, 11156, 11419,
             11732, 12796, 12848, 13269],
            dtype='int64'),
 'TurboGrafx-CD': Int64Index([10491, 10699, 11823], dtype='int64'),
 'Vectrex': Int64Index([11169, 11172], dtype='int64'),
 'Web Games': Int64Index([16594], dtype='int64'),
 'Wii': Int64Index([  139,   316,  8493,  8495,  8568,  8571,  8582,  8594,  8598,
              8611,
             ...
             16566, 16589, 16598, 16619, 16670, 16737, 16830, 17108, 17346,
             17374],
            dtype='int64', length=1366),
 'Wii U': Int64Index([  259,   265,   271,   276,   279,   280,   292,   294,   296,
               304,
             ...
             18321, 18322, 18341, 18429, 18431, 18476, 18477, 18499, 18544,
             18620],
            dtype='int64', length=114),
 'Windows Phone': Int64Index([15166, 15194, 15197, 15198, 15200, 15203, 15213, 15224, 15228,
             15232, 15268, 15272, 17241, 17540],
            dtype='int64'),
 'Windows Surface': Int64Index([17242], dtype='int64'),
 'Wireless': Int64Index([ 4673,  4694,  4698,  4778,  4780,  4781,  4783,  4784,  4785,
              4808,
             ...
             12042, 12084, 12132, 12172, 12181, 12226, 12310, 12578, 12710,
             15240],
            dtype='int64', length=910),
 'WonderSwan': Int64Index([2074, 2092, 2121, 2200], dtype='int64'),
 'WonderSwan Color': Int64Index([2974], dtype='int64'),
 'Xbox': Int64Index([3365, 3425, 3426, 3427, 3432, 3435, 3440, 3441, 3443, 3444,
             ...
             8577, 8624, 8675, 8680, 8684, 8710, 8718, 8960, 9514, 9636],
            dtype='int64', length=821),
 'Xbox 360': Int64Index([    3,     6,    11,    13,    19,    21,    37,    40,    44,
                47,
             ...
             17931, 17935, 17940, 17948, 17952, 17955, 18002, 18043, 18323,
             18328],
            dtype='int64', length=1631),
 'Xbox One': Int64Index([17137, 17197, 17295, 17313, 17314, 17315, 17316, 17317, 17328,
             17335,
             ...
             18565, 18571, 18582, 18585, 18588, 18591, 18597, 18602, 18611,
             18623],
            dtype='int64', length=208),
 'iPad': Int64Index([    2,    26,    52,   121,   137,   206,   247,   287,   328,
               351, 14326, 14329, 14330, 14331, 14332, 14333, 14334, 14335,
             14337, 14338, 14368, 14376, 14394, 14402, 14403, 14432, 14435,
             14441, 14442, 14471, 14490, 14501, 14503, 14511, 14533, 14536,
             14548, 14596, 14599, 14624, 14700, 14706, 14707, 14716, 14788,
             14789, 14801, 14804, 14814, 14862, 14866, 14881, 14917, 14928,
             15065, 15120, 15218, 15318, 15335, 15364, 15381, 15391, 15402,
             15436, 15447, 15449, 15479, 15497, 15519, 15553, 15604, 15661,
             15699, 15732, 15742, 15752, 15767, 15792, 15842, 15854, 15921,
             16027, 16053, 16065, 16140, 16454, 16765, 16846, 16955, 17056,
             17087, 17252, 17508, 17615, 17697, 17829, 18036, 18137, 18338],
            dtype='int64'),
 'iPhone': Int64Index([   12,    17,    36,    45,    49,    54,    62,    76,    77,
                86,
             ...
             18156, 18182, 18184, 18188, 18222, 18229, 18286, 18372, 18419,
             18607],
            dtype='int64', length=842),
 'iPod': Int64Index([ 8249,  8257,  8290,  8294,  8295,  8296,  8321,  9358,  9544,
             10367, 10370, 10382, 10462, 10472, 10537, 10681, 10907],
            dtype='int64')}

In [28]:
platform_group.size()

platform
Android                   39
Arcade                    11
Atari 2600                 5
Atari 5200                 2
Commodore 64/128           6
DVD / HD Video Game        1
Dreamcast                286
Dreamcast VMU              1
Game Boy                  22
Game Boy Advance         623
Game Boy Color           356
Game.Com                   3
GameCube                 509
Genesis                   58
Linux                     10
Lynx                      82
Macintosh                 81
Master System             13
N-Gage                    30
NES                       49
NeoGeo                    10
NeoGeo Pocket Color       31
New Nintendo 3DS           2
Nintendo 3DS             225
Nintendo 64              302
Nintendo 64DD              7
Nintendo DS             1045
Nintendo DSi             254
Ouya                       1
PC                      3370
PlayStation              952
PlayStation 2           1686
PlayStation 3           1356
PlayStation 4            277
PlayStation Portable     633
PlayStation Vita         155
Pocket PC                  1
Saturn                     6
Sega 32X                  16
Sega CD                    1
SteamOS                    1
Super NES                 33
TurboGrafx-16             40
TurboGrafx-CD              3
Vectrex                    2
Web Games                  1
Wii                     1366
Wii U                    114
Windows Phone             14
Windows Surface            1
Wireless                 910
WonderSwan                 4
WonderSwan Color           1
Xbox                     821
Xbox 360                1631
Xbox One                 208
iPad                      99
iPhone                   842
iPod                      17
dtype: int64

In [18]:
genre_grou=movie_reviews.groupby('genre')
#genre_group.groups

In [20]:
genre_grou.size()

genre
Action                      3797
Action, Adventure            765
Action, Compilation           89
Action, Editor                 1
Action, Platformer             3
Action, Puzzle                 1
Action, RPG                  330
Action, Simulation            32
Action, Strategy               1
Adult, Card                    2
Adventure                   1175
Adventure, Adult               1
Adventure, Adventure           5
Adventure, Compilation        11
Adventure, Episodic            4
Adventure, Platformer          1
Adventure, RPG                 3
Baseball                       1
Battle                        32
Board                        116
Board, Compilation             7
Card                         108
Card, Battle                  54
Card, Compilation              3
Card, RPG                      9
Casino                        31
Compilation                   54
Compilation, Compilation       1
Compilation, RPG               2
Educational                   20
                            ...
Racing, Compilation            2
Racing, Editor                 3
Racing, Shooter                2
Racing, Simulation            25
Shooter                     1610
Shooter, Adventure             1
Shooter, First-Person          4
Shooter, Platformer            3
Shooter, RPG                  22
Simulation                   567
Simulation, Adventure          1
Sports                      1916
Sports, Action               196
Sports, Baseball               3
Sports, Compilation           14
Sports, Editor                 1
Sports, Fighting               1
Sports, Golf                   1
Sports, Other                  1
Sports, Party                  1
Sports, Racing                 5
Sports, Simulation            44
Strategy                    1071
Strategy, Compilation          1
Strategy, RPG                 77
Strategy, Simulation           1
Trivia                       119
Virtual Pet                   82
Wrestling                    134
Wrestling, Simulation          1
Length: 112, dtype: int64

In [23]:
editors_group = movie_reviews.groupby('editors_choice')
editors_group.groups
editors_group.size()

editors_choice
N    15108
Y     3517
dtype: int64

In [26]:
scorephrase_group = movie_reviews.groupby('score_phrase')
scorephrase_group.groups
scorephrase_group.size()

score_phrase
Amazing        1804
Awful           664
Bad            1269
Disaster          3
Good           4741
Great          4773
Masterpiece      55
Mediocre       1959
Okay           2945
Painful         340
Unbearable       72
dtype: int64

In [25]:
# you can also use a loop to manually iterate through the groups:
for name, group in scorephrase_group:
    print(name)
    print(group.shape)

Amazing
(1804, 11)
Awful
(664, 11)
Bad
(1269, 11)
Disaster
(3, 11)
Good
(4741, 11)
Great
(4773, 11)
Masterpiece
(55, 11)
Mediocre
(1959, 11)
Okay
(2945, 11)
Painful
(340, 11)
Unbearable
(72, 11)

In [37]:
scorephrase_group.agg(np.mean)
#from this we can infer that all people who have given masterpiece as a
#scorephrase has also given score of 10

,Unnamed: 0,score,release_year,release_month,release_day
score_phrase,,,,,
Amazing,9295.829268,9.176663,2006.973947,7.308758,15.724501
Awful,8316.013554,3.290211,2005.493976,7.073795,15.551205
Bad,9194.383767,4.331600,2006.230890,7.214342,15.227738
Disaster,6215.000000,0.666667,2003.333333,7.333333,22.666667
Good,9482.637418,7.369099,2006.646066,7.143430,15.579625
Great,9397.675676,8.316510,2006.552902,7.116070,15.799078
Masterpiece,10687.490909,10.000000,2007.527273,6.836364,18.945455
Mediocre,9295.916794,5.318530,2006.438489,7.122001,15.364982
Okay,9311.861460,6.366553,2006.504584,7.071647,15.608829
Painful,8440.623529,2.267941,2005.561765,7.035294,14.679412
Unbearable,7696.194444,1.290278,2004.750000,7.180556,16.166667

In [46]:
score_group = movie_reviews.groupby(['score','score_phrase'])
score_group.groups
score_group.size()
#so we can say that score_phrase feature is not user selected

score  score_phrase
0.5    Disaster           1
0.7    Disaster           1
0.8    Disaster           1
1.0    Unbearable        33
1.1    Unbearable         1
1.2    Unbearable         4
1.3    Unbearable         1
1.4    Unbearable         1
1.5    Unbearable        22
1.7    Unbearable         3
1.8    Unbearable         1
1.9    Unbearable         6
2.0    Painful          151
2.1    Painful           15
2.2    Painful           15
2.3    Painful           15
2.4    Painful            6
2.5    Painful          100
2.6    Painful            5
2.7    Painful            9
2.8    Painful           12
2.9    Painful           12
3.0    Awful            296
3.1    Awful             13
3.2    Awful             16
3.3    Awful             22
3.4    Awful             15
3.5    Awful            209
3.6    Awful             16
3.7    Awful             18
                       ...
7.1    Good             136
7.2    Good             231
7.3    Good             220
7.4    Good             226
7.5    Good            1086
7.6    Good             183
7.7    Good             250
7.8    Good             465
7.9    Good             371
8.0    Great           1758
8.1    Great            158
8.2    Great            301
8.3    Great            280
8.4    Great            312
8.5    Great           1026
8.6    Great            181
8.7    Great            225
8.8    Great            320
8.9    Great            212
9.0    Amazing          917
9.1    Amazing          141
9.2    Amazing          146
9.3    Amazing          160
9.4    Amazing          110
9.5    Amazing          230
9.6    Amazing           47
9.7    Amazing           28
9.8    Amazing           19
9.9    Amazing            6
10.0   Masterpiece       55
Length: 93, dtype: int64